language: node_js
node_js:
- node
- 8
- 6
cache: yarn
git:
  depth: 3
after_success:
- yarn run coverage
script:
- yarn run test:ci
deploy:
  provider: npm
  email: i@charugin.ru
  api_key:
    secure: R/oJjHJcfSxyOudJTiAw5pLpmyCgU0wDr9myazxYalDpSLL8LUyIX1RXKMViynGFSWaYepNXIrPnqFQKAHMSV5mGM2h9cDU3Mb0WAzRWcQz5GXM0nTUPu6VE3bFAmx4WNldx94bM/5BD2B/zmMiXnuAkbbP1JqHEFEW0697cX9pp2eeC/W/D5erXdJnFOSMEJzt3cQV2+JId+JEK7YD7UadKlWHarkHzkKnNwpK0H4pqMroONlToq7+qx3Ul6B06pu1ePRhDLZPAgiF+U4dmsEiTf5zA0+EiwC0cTogDOcDab1ijEsRTG5fB+BJK5mCPwZNQDuQf292+psAWFMbBwL7gBXjHqOlLs0/B/pAemT0+dYVbzMjAPVXjoU4oBzl+FwGDPp4w8DJRYCcczYCYJ5TK+OfxG67cENNoeRGjZ0XK6yCR2+wML2bjDi0A/mkSmMELZd5Hz4pbngiJqLxOd0e0n0RV5yO3YU0cNleic+DQ8ODrc7xP4ndlvHKVkYp0zqn/9GdinWh4W4qRwvdGiuPeinLVNs7TM8J4ZnQ9w8X4fDjqz9gVPLxyFNuCYR+1x/kcorY2iNoTJjFohVvNFcT7z2Vo68Rjgs5zxEJ6gWBjev31dx0hVAYNPxRl2KMvzkrJ1GVR+YjfAJ3j+Zi0AFEST0U0gb1hNkjj1lZg8Gw=
  on:
    tags: true
    repo: RomiC/ya-disk-stream
